In [78]:
a = input('输入数字')
b = a.split(',')
c = tuple(b)
print(b,c)

输入数字 651,7498,65


['651', '7498', '65'] ('651', '7498', '65')


In [26]:
#这题不会
class inout:
    def __init__(self):
        self.s = ''
    def getString(self):
        self.s = input('输入字符串:')
    def printString(self):
        print('输出字符串:',self.s.upper())
gg = inout()
gg.getString()
gg.printString()

输入字符串: asdpoijwdj


输出字符串: ASDPOIJWDJ


In [44]:
#不熟
def compute(D):
    D = D.split(',')
    C,H = 50,30
    result=[]
    for i in range(len(D)):
        Q = ((2*C*int(D[i]))/H)**(1/2)
        result.append(str(round(Q)))
    print(','.join(result))
    

compute(input('输入D'))

输入D 100,150,180


18,22,24


In [63]:
#不熟
import numpy as np
c=input("输入两数字，逗号分隔")
c=c.split(',')

x = int(c[0])
y = int(c[1])
result=np.zeros((x,y))
for i in range(x):
    for j in range(y):
        result[i][j]=i*j
print(result)

输入两数字，逗号分隔 3,5


[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


In [61]:
x,y = map(int,input().split(','))
lst = []

for i in range(x):
    tmp = []
    for j in range(y):
        tmp.append(i*j)
    lst.append(tmp)

print(lst)


 3,5


[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]


In [69]:
#这题不会
lst = input().split(',')
lst.sort()
print(','.join(lst))

 without,hello,bag,world


bag,hello,without,world


In [99]:
#还是不会
lst = []

while True:
    x = input()
    if len(x)==0:
        break
    lst.append(x.upper())

for line in lst:
    print(line)


 Hello world Practice makes perfect
 


HELLO WORLD PRACTICE MAKES PERFECT


输入D的数值 100,150,180


18,22,24


输入XY 3,5


[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]


 Hello world Practice makes perfect


HELLO WORLD PRACTICE MAKES PERFECT
