In [25]:
lst = [5,6,77,45,22,12,24]
fb = lst.copy()

for i in range(len(lst)):
    if lst[i]%2==0:
        fb.remove(lst[i])
print(fb)

'''li = [5,6,77,45,22,12,24]
lst = [i for i in li if i%2!=0]
print(lst)'''

[5, 77, 45]


In [26]:
def isEven(n):
    return n%2!=0
li = [5,6,77,45,22,12,24]
lst = list(filter(isEven,li))
print(lst)

[5, 77, 45]


In [27]:
def isd35(n):
    return n%35!=0
li = [12,24,35,70,88,120,155]
lst = list(filter(isd35,li))
print(lst)

[12, 24, 88, 120, 155]


In [38]:
lst = [12,24,35,70,88,120,155]
li = lst.copy()
for i in range(len(lst)):
    if i%2==0:
        li.remove(lst[i])
li

[24, 70, 120]

In [39]:
li = [12,24,35,70,88,120,155]
li = [x for (i,x) in enumerate(li) if i%2!=0]
print(li)

[24, 70, 120]


In [41]:
li = [12,24,35,70,88,120,155]
li = [x for (i,x) in enumerate(li) if not 2<=i<=4]
print(li)

[12, 24, 120, 155]


In [44]:
import numpy as np
a = np.zeros((3,5,8))
print(a.shape,a)
'''array = [[ [0 for col in range(8)] for col in range(5)] for row in range(3)]
print array
'''

(3, 5, 8) [[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]
